baseURL = "https://claudiaguerreros.github.io/mapas/"
languageCode = "en-us"
title = "Mapas Económicos"
themesDir="themes"
theme = "minimal"
publishDir="docs"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""



[params]
    author = "Claudia Guerrero"
    description = "Sitio de mapas económicos"
    githubUsername = "#"
    accent = "navy"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Inicio"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/proyecto/"
    name = "Proyectos"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:cgsguerrero@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/claudiaguerreros/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/guerreroclaudia/"
    name = "twitter"
    weight = 3


